# https://mangowm.github.io/docs/

monitorrule = name:eDP-(1|2), width:1920, height:1080, refresh:144.0, vrr:1

source = ~/.config/mango/exec.conf
source = ~/.config/mango/binds.conf
source = ~/.config/mango/options.conf
source = ~/.config/mango/rules.conf
source = ~/.config/mango/animations.conf
source = ~/.config/mango/env.conf
source = ~/.config/mango/colors/colors.conf