#    ▄▄▄█████ ▄▄        ▄▄    ▄▄▄█████    ▄▄▄█████
#  ▄▄███████▓ ██▄▄    ▄▄██  ▄▄███████▓  ▄▄███████▓
# ▄███▀▀▀███▒ ████    ████ ▄███▀▀▀███▒ ▄███▀▀▀███▒
# ▓▓▓▓▀  ███░ ▓▓▓▓    ▓▓▓▓ ▓▓▓▓▀  ███░ ▓▓▓▓▀  ███░
# ▓▓▓▓   █▀▀  ▀▀▓▓▄  ▄▓▓▀▀ ▓▓▓▓   █▀▀  ▓▓▓▓   █▀▀ 
# ████▄▄▄      ▄████████▄  ████▄▄▄     ████       
# ██████▀ ▓▓▓ ▄▓▓▓▀▀▀▀▓▓▓▄ ██████▀ ▓▓▓ ████    ▓▓▓
# ████▀   ███ ▒▒▒▒    ▒▒▒▒ ████▀   ███ ████▄   ███
# ▀▀█████████ ▀░░░    ░░░▀ ▀▀█████████ ▀▀█████████
#   ▀▀▀▄█████   ▀▀    ▀▀     ▀▀▀▄█████   ▀▀▀▄█████
# 
# https://mangowm.github.io/docs/configuration/basics

exec-once = awww-daemon
exec-once = waybar
exec-once = swaync
exec-once = gammastep-indicator
exec-once = hypridle

exec-once = /usr/lib/xfce-polkit/xfce-polkit

exec-once = wl-clip-persist --clipboard regular
exec-once = wl-paste --type text --watch cliphist -max-items=35 store
exec-once = wl-paste --type image --watch cliphist -max-items=10 store

exec-once = ~/.local/bin/dock

exec-once = ~/.local/bin/at_startup
