#!/bin/bash

cd $HOME/.config/nwg-dock-hyprland/colors

if [[ "$1" == "dark" ]]; then
    ln -fs colors.dark.css colors.css
else
    ln -fs colors.light.css colors.css
fi

pkill -f nwg-dock-hyprland

"$HOME/.local/bin/dock" &
