#!/bin/bash

WALLPAPER_LIGHT_DEF="$HOME/med/pictures/wallpapers/dragons_lake_fog_white_boat_person.jpg"
WALLPAPER_DARK_DEF="$HOME/med/pictures/wallpapers/rain_road_tree_foggy_bush_flowers_girl_umbrela_grey_outside_mountain.jpg"

WALLPAPER_LIGHT="${WALLPAPER_LIGHT:-$WALLPAPER_LIGHT_DEF}"
WALLPAPER_DARK="${WALLPAPER_DARK:-$WALLPAPER_DARK_DEF}"

THEMESW_DIR="$HOME/.config/themesw/"

if [[ -f "$THEMESW_DIR/wallpaper.last.$1" ]]; then
    WALLPAPER=$(< "$THEMESW_DIR/wallpaper.last.$1")
else
    if [[ $1 == "dark" ]]; then
        WALLPAPER=$WALLPAPER_DARK
    else
        WALLPAPER=$WALLPAPER_LIGHT
    fi
fi

CURRENT_WALLPAPER=$(awww query -j | jq -r '.[""][].displaying.image')

if [[ $CURRENT_WALLPAPER != $WALLPAPER ]]; then
    ~/.local/bin/auto_walls set $WALLPAPER &
fi
