#!/bin/bash

cd "$HOME/.config/spicetify/Themes/Custom/"

if [[ "$1" == "dark" ]]; then
    ln -fs css/dark.css user.css
else
    ln -fs css/light.css user.css
fi

spicetify refresh

if pgrep -x "spotify" ; then
    pkill -x "spotify"

    if [[ "$MANGO_INSTANCE_SIGNATURE" ]]; then 
        mmsg dispatch spawn, spotify-launcher
    else 
        hyprctl dispatch 'hl.dsp.exec_raw("spotify-launcher")'
    fi
fi
