#!/bin/bash

cd "$HOME/.config/spicetify/Themes/Custom/"

if [[ "$1" == "dark" ]]; then
    ln -fs css/dark.css user.css
else
    ln -fs css/light.css user.css
fi

spicetify refresh

if pgrep -x "spotify" ; then
    pkill -x "spotify"
    hyprctl dispatch 'hl.dsp.exec_raw("spotify-launcher")'
fi
