#!/usr/bin/env python3
from subprocess import run
from os import system
import json

workspace_info = run(
    ["hyprctl", "activeworkspace", "-j"], 
    capture_output=True, 
    text=True, 
    check=True
)

info = json.loads(workspace_info.stdout)

if info["tiledLayout"] == "scrolling":
    target_layout = "dwindle"
else:
    target_layout = "scrolling"

system(f"hyprctl keyword workspace {info["id"]}, layout:{target_layout}")
system(f"hyprctl keyword workspace {info["id"]}, layout:{target_layout}")