# Active window border
focuscolor  = 0x343B58FF

# Inactive window border
bordercolor = 0xD6D8DFDB

# Shadow when dragging windows
dropcolor   = 0x343B5805

splitcolor          = 0xEB441EFF
maximizescreencolor = 0xE0AF68FF
urgentcolor         = 0xF7768EFF
scratchpadcolor     = 0xACB0D0FF
globalcolor         = 0xACB0D0FF
overlaycolor        = 0x41A6B5FF
