# Active window border
focuscolor  = 0x787C99FF

# Inactive window border
bordercolor = 0x0A0A0DDB # ABOBOBA

# Shadow when dragging windows
dropcolor   = 0x787C9905

# TODO These are default, change later
splitcolor          = 0xEB441EFF
maximizescreencolor = 0xBABD2Cff
urgentcolor         = 0xad401fff
scratchpadcolor     = 0xc4939dff
globalcolor         = 0x8d64cfff
overlaycolor        = 0x95C381ff
