[window]
dynamic_title = false
padding.x = 10
padding.y = 10

[font]
normal.family = "CaskaydiaCove Nerd Font Propo"
normal.style = "Bold"
size = 13

[cursor]
# style.shape = "Beam"
style.shape = "Underline"
style.blinking = "On"

[selection]
save_to_clipboard = true

[general]
import = [
  "~/.config/alacritty/theme.toml",
  "~/.config/alacritty/binds.toml"
]
